baseURL = "https://it-for-kids.org/"
languageCode = "de-de"
title = "IT4Kids | IT-Kurse für Grundschulen"

copyright = "<span class=\"copyright\">Copyright &copy; <script>document.write(new Date().getFullYear())</script> IT4Kids</span>"

[permalinks]
  blog = "/blog/:year/:month/:title/"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = -100

  [[menu.main]]
    name = "Vision"
    url = "/vision/"
    weight = -90

  [[menu.main]]
    name = "Lehrmaterial"
    weight = -80

 [[menu.main]]
      name = "Projekte"
      parent = "Lehrmaterial"
      url = "/projekte/"

  [[menu.main]]
      name = "Inhalte"
      parent = "Lehrmaterial"
      url = "/lehrmaterial/"

  [[menu.main]]
    name = "Software"
    url = "/software/"
    parent = "Lehrmaterial"


  [[menu.main]]
    name = "Kursangebot"
    weight = -70

      [[menu.main]]
        name = "Für Schulen"
        parent = "Kursangebot"
        url = "/schulen/"
        weight = -20

      [[menu.main]]
        name = "Für Kursleiter"
        parent = "Kursangebot"
        url = "/mitmachen/"
        weight = -10


  [[menu.main]]
    name = "Über uns"
    weight = -60

      [[menu.main]]
          name = "Status"
          parent = "Über uns"
          url = "/status/"

      [[menu.main]]
        name = "Team"
        parent = "Über uns"
        url = "/team/"

      [[menu.main]]
        name = "Blog"
        parent = "Über uns"
        url = "/blog/"

[params]
  facebook = "https://www.facebook.com/itforkids.org/"
  instagram = "https://www.instagram.com/it4kids.ac/"
  enactus = "https://enactus.de/aachen/"
  title = "IT4Kids | IT-Kurse für Grundschulen"
  images = ["/img/ms-icon-310x310.png"]
  description = "IT4Kids bietet spielerische IT-Kurse für Grundschulen, die Logik- und Prozess-Denken stärken."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
