baseURL = "https://it-for-kids.org/"
languageCode = "de-de"
title = "IT4Kids"

copyright = "<span class=\"copyright\">Copyright &copy; <script>document.write(new Date().getFullYear())</script> IT4Kids</span>"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = -100

  [[menu.main]]
    name = "Vision"
    url = "/vision/"
    weight = -90

  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = -80

  [[menu.main]]
    name = "Lehrmaterial"
    weight = -70

 [[menu.main]]
      name = "Projekte"
      parent = "Lehrmaterial"
      url = "/projekte/"

  [[menu.main]]
      name = "Inhalte"
      parent = "Lehrmaterial"
      url = "/lehrmaterial/"

  [[menu.main]]
    name = "Kurse"
    weight = -60

  [[menu.main]]
    name = "Kursleiter"
    parent = "Kurse"
    url = "/mitmachen/"

  [[menu.main]]
    name = "Schulen"
    parent = "Kurse"
    url = "/schulen/"

  [[menu.main]]
    name = "Wir"
    weight = -60

  [[menu.main]]
    name = "Team"
    parent = "Wir"
    url = "/team/"

  [[menu.main]]
    name = "Blog"
    parent = "Wir"
    url = "/blog/"

[params]
  facebook = "https://www.facebook.com/itforkids.org/"
  enactus = "https://enactus.de/aachen/"
